### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by alvarocasadoc** [FragmentX/FRAGMENTX#2]
Our main goal is to redesign the app to improve user experience.

Issues:
- [x] #5 [Redesign app homepage][1]
- [x] #9 [Redesign 3d visor][2]
- [x] #11 [Auth pages redesign][3]
- [x] #13 [Make signup and login links dynamic][4]
- [x] #12 [Add favicon][5]
- [x] #10 [Object index redesign][6]

[1]: https://github.com/FragmentX/FRAGMENTX/issues/5
[2]: https://github.com/FragmentX/FRAGMENTX/issues/9
[3]: https://github.com/FragmentX/FRAGMENTX/issues/11
[4]: https://github.com/FragmentX/FRAGMENTX/issues/13
[5]: https://github.com/FragmentX/FRAGMENTX/issues/12
[6]: https://github.com/FragmentX/FRAGMENTX/issues/10
